"""CLI entrypoint for the eval-dataset build steps.

The dataset is generated by `deepeval generate`, not by this file. These are
the two steps that bracket it — see `tests/evals/README.md` for the full
sequence:

    cms-evalset export-contexts    # before: corpus -> tests/evals/contexts.json
    deepeval generate ...          # the LLM step
    cms-evalset annotate           # after:  raw goldens -> tests/evals/.dataset.json

Both steps are free and offline; only the middle one costs money. Splitting
them this way means the contexts can be inspected, and a bad annotate re-run
does not mean paying for generation twice.
"""

import argparse
import logging
import sys
from pathlib import Path

# The `cms.config` import must come first: importing it runs cms/config/__init__.py,
# which injects the OS trust store into ssl. That has to happen before any HTTPS
# client is constructed.
from cms.config.logging_config import setup_logging
from cms.evals.dataset import annotate_goldens, build_contexts, write_contexts_file

logger = logging.getLogger("cms.cli.evalset")

EVAL_DIR = Path("tests/evals")
DEFAULT_CONTEXTS = EVAL_DIR / "contexts.json"
DEFAULT_RAW_GOLDENS = EVAL_DIR / "generated.json"
DEFAULT_DATASET = EVAL_DIR / ".dataset.json"

# 26 + 14 = 40 contexts at --max-goldens-per-context 1. Deliberately above the
# 30-40 target: deepeval's filtration drops goldens below its quality
# threshold, so generating exactly 30 would land under it.
DEFAULT_POLICY_LIMIT = 26
DEFAULT_CASE_LIMIT = 14


def _export_contexts(args: argparse.Namespace) -> int:
    contexts = build_contexts(policy_limit=args.policies, case_limit=args.cases)

    if args.dry_run:
        print(f"{len(contexts)} context(s) selected — no files written\n")
        for context in contexts:
            print(f"  {context.header()}  [{len(context.chunks)} chunk(s)]")
        return 0

    count = write_contexts_file(contexts, args.out)
    print(f"Wrote {count} context(s) to {args.out}")
    print(f"Next: deepeval generate --method contexts --contexts-file {args.out} ...")
    return 0


def _annotate(args: argparse.Namespace) -> int:
    count = annotate_goldens(args.goldens, args.out)
    print(f"Wrote {count} golden(s) to {args.out}")
    return 0


def main() -> int:
    setup_logging()

    # Seed-corpus text is arbitrary UTF-8 (₹, em dashes, accents); Windows
    # terminals default stdout to the system codepage (cp1252), which cannot
    # encode it — see the identical fix in cli/retrieve.py.
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")

    parser = argparse.ArgumentParser(
        description="Build the eval dataset around `deepeval generate`."
    )
    subparsers = parser.add_subparsers(dest="command", required=True)

    export = subparsers.add_parser(
        "export-contexts",
        help="Turn the seed corpus into the contexts file `deepeval generate "
        "--method contexts` reads.",
    )
    export.add_argument(
        "--policies",
        type=int,
        default=DEFAULT_POLICY_LIMIT,
        help=f"How many policy contexts to select (default: {DEFAULT_POLICY_LIMIT}).",
    )
    export.add_argument(
        "--cases",
        type=int,
        default=DEFAULT_CASE_LIMIT,
        help=f"How many case contexts to select (default: {DEFAULT_CASE_LIMIT}).",
    )
    export.add_argument("--out", type=Path, default=DEFAULT_CONTEXTS)
    export.add_argument(
        "--dry-run",
        action="store_true",
        help="Print the selection and write nothing.",
    )
    export.set_defaults(func=_export_contexts)

    annotate = subparsers.add_parser(
        "annotate",
        help="Attach ground-truth metadata to the generated goldens.",
    )
    annotate.add_argument("--goldens", type=Path, default=DEFAULT_RAW_GOLDENS)
    annotate.add_argument("--out", type=Path, default=DEFAULT_DATASET)
    annotate.set_defaults(func=_annotate)

    args = parser.parse_args()

    try:
        return args.func(args)
    except Exception:
        logger.exception("cms-evalset %s failed", args.command)
        return 1


if __name__ == "__main__":
    sys.exit(main())
