-- 0005_cases.sql — resolved complaints, the experiential half of the knowledge base.
--
-- Cases and policies are deliberately *separate* tables backed by *separate*
-- Qdrant collections. They are not two flavours of one thing: a case is a
-- record of what we did once, generated by the system; a policy is an authored
-- document that states what we are allowed to do, governed by humans. They
-- differ in where they come from, who may write them, how they chunk, and how
-- they are approved — so they do not share a status vocabulary or a grant set.
--
-- The complaint / guidance / resolution split is stored structurally rather than
-- pre-flattened into one text blob. Retrieval still embeds the flattened form,
-- but the columns stay queryable and the flattening stays a projection.

CREATE TABLE IF NOT EXISTS cases (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    -- Natural key of the seed corpus ('C-1001'); NULL for flywheel cases, whose
    -- identity is the ticket they came from.
    source_ref      TEXT UNIQUE,
    ticket_id       UUID REFERENCES tickets(id) ON DELETE SET NULL,
    title           TEXT NOT NULL,              -- display label for citation cards
    department_id   TEXT NOT NULL REFERENCES departments(id),
    category        TEXT,

    complaint_text  TEXT NOT NULL,
    dept_guidance   TEXT,                       -- Path B (escalated) cases only
    resolution_text TEXT NOT NULL,
    resolution_path TEXT CHECK (resolution_path IN ('direct', 'escalated')),

    -- No 'upload': a case is never a file someone drags in. It is seeded, or it
    -- is minted from a resolved ticket.
    source          TEXT NOT NULL DEFAULT 'flywheel' CHECK (source IN ('seed', 'flywheel')),

    -- Ingestion lifecycle. 'deleting' exists so delete/replace can be crash-safe:
    -- Qdrant points are removed first, then Postgres. A crash between the two
    -- leaves a visible, resumable row.
    status          TEXT NOT NULL DEFAULT 'pending'
                    CHECK (status IN ('pending', 'processing', 'indexed', 'failed', 'deleting')),
    content_hash    TEXT,                       -- lets the pipeline short-circuit unchanged cases
    chunk_count     INT NOT NULL DEFAULT 0,
    error           TEXT,

    created_by      UUID REFERENCES profiles(id) ON DELETE SET NULL,  -- NULL = system/flywheel
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    indexed_at      TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS idx_cases_status ON cases(status);
CREATE INDEX IF NOT EXISTS idx_cases_dept   ON cases(department_id);
CREATE INDEX IF NOT EXISTS idx_cases_hash   ON cases(content_hash);
CREATE INDEX IF NOT EXISTS idx_cases_ticket ON cases(ticket_id);

DROP TRIGGER IF EXISTS trg_cases_updated_at ON cases;
CREATE TRIGGER trg_cases_updated_at
    BEFORE UPDATE ON cases
    FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ---------------------------------------------------------------------------
-- RLS — shared org knowledge base (D2), read-only to agents
-- ---------------------------------------------------------------------------
-- SELECT only, deliberately. Cases are written by the seed script and by the
-- flywheel, both of which run as the service role and bypass RLS. Granting an
-- agent INSERT here would let them hand-write a "resolved case" straight into
-- the retrieval corpus, which is a corpus-poisoning vector: every future draft
-- would cite it as precedent. The absence of INSERT/UPDATE/DELETE policies is
-- the mechanism — with RLS on and no policy for a command, that command is
-- denied to everyone but the service role.

ALTER TABLE cases ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS cases_select_all ON cases;
CREATE POLICY cases_select_all ON cases
    FOR SELECT TO authenticated
    USING (true);
